esphome:
  name: sgp40-dht22

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "abcdefg-changeme"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sgp40-Dht22 Fallback Hotspot"
    password: "abcdefg-changeme"

captive_portal:

i2c:
  sda: SDA
  scl: SCL
  scan: True
  frequency: 1kHz
  
sensor:
  - platform: dht
    model: RHT03
    pin: D5
    temperature:
      name: "SGP40_Temperature"
      id: dht_temp
    humidity:
      name: "SGP40_Humidity"
      id: dht_humidity
    update_interval: 30s

  - platform: sgp40
    name: "SGP40 VOC"
    update_interval: 30s
    compensation:
      humidity_source: dht_humidity
      temperature_source: dht_temp
      
